version: '2'
services:
    registryservice:
        build: registryservice
        mem_limit: 512M
        ports:
            - "8761:8761"
    configservice:
        build: configservice
        entrypoint: /opt/spring-cloud/bin/config-service-entrypoint.sh
        mem_limit: 512M
        ports:
            - "8888:8888"
        links:
            - registryservice:registryservice
        depends_on:
            - registryservice
    counterservice:
        build: counterservice
        entrypoint: /opt/spring-cloud/bin/config-client-entrypoint.sh
        mem_limit: 512M
        ports:
            - "8080:8080"
        links:
            - configservice:configservice
            - registryservice:registryservice
        depends_on:
            - configservice
            - registryservice
    gatewayservice:
        build: gatewayservice
        mem_limit: 512M
        ports:
            - "9999:9999"
        links:
            - counterservice:counterservice
            - registryservice:registryservice
        depends_on:
            - counterservice
            - registryservice
